// eslint-disable-line
export const text = {
    addToCart:                          'Купить',
    cart:                               'Корзина',
    cartEmpty:                          'Ваша корзина пуста',
    proceedToCheckout:                  'Оформить заказ',
    subtotal:                           'Сумма товаров',
    shipping:                           'Доставка',
    discount:                           'Скидка',
    tax:                                'Tax',
    included_tax:                       'Included Tax',
    total:                              'Сумма',
    remove:                             'Удалить',
    qty:                                'Количество',
    price:                              'Цена',
    product_variant_id:                 'Номер опции',
    product_id:                         'Номер товара',
    order_line_id:                      'Номер заказа',
    product_image:                      'Картинка',
    product_discount_total:             'Скидка',
    product_name:                       'Название',
    product_qty:                        'Количество',
    product_price:                      'Цена',
    product_price_total:                'Сумма',
    product_sku:                        'Артикул',
    product_tax_class:                  'Ставка налога',
    product_tax_total:                  'Сумма налога',
    product_variant_name:               'Опции товара',
    product_weight:                     'Вес товара',
    checkoutPageTitle:                  'Оформление заказа',
    grandTotal:                         'К оплате',
    orderSummary:                       'Ваш заказ',
    cardNumber:                         'Номер карты',
    expirationDate:                     'Дата',
    CVC:                                'CVC',
    pay:                                'Оплатить',
    checkoutSuccessTitle:               'Спасибо за ваш заказ!',
    outOfStock:                         'Нет в наличии',
    inStock:                            'В наличии',
    discontinued:                       'Снято с продажи',
    relatedProducts:                    'Вас может заинтересовать',
    filterProducts:                     'Фильтр товаров',
    sort:                               'Сортировка',
    sortFavorite:                       'По умолчанию',
    sortRelevant:                       'По релевантности',
    sortNewest:                         'Новинки',
    sortPriceLow:                       'от дешевых к дорогим',
    sortPriceHigh:                      'от дорогих к дешевым',
    title404:                           'Запрашиваемая страница не найдена!',
    loadMore:                           'Показать еще',
    loadMoreProducts:                   'Показать еще товары',
    text404:                            'К сожалению, запрашиваемая Вами страница не найдена.',
    text404Row2:                        'Вероятно, Вы указали несуществующий адрес, страница была удалена, перемещена или сейчас она временно недоступна!',    
    text404Row3:                        'Вы можете воспользоваться поиском по сайту или меню.',
    search:                             'Поиск',
    searchResult:                       'Результаты поиска',
    searchPlaceholder:                  'Поиск',
    resultsFor:                         'Результаты по запросу',
    selectOption:                       'Выберите',
    optionsRequired:                    'Выберите опции товара',
    shippingAddress:                    'Адрес доставки',
    billingAddress:                     'Платежный адрес',
    shippingMethod:                     'Способ доставки',
    paymentMethod:                      'Способ оплаты',
    orderNumber:                        'Номер заказа',
    productName:                        'Название товара',
    close:                              'Закрыть',
    attributes:                         'Свойства',
    home:                               'Главная',
    saleEnds:                           'До конца акции осталось',
    days:                               'дни',
    hours:                              'час',
    minutes:                            'мин',
    seconds:                            'сек',
    email:                              'Email',
    password:                           'Пароль',
    password_verify:                    'Подтвердите пароль',
    mobile:                             'Мобильный',
    country:                            'Страна',
    state:                              'Область',
    city:                               'Город',
    street:                             'Улица',
    house:                              'Дом',
    room:                               'Квартира/Офис',
    DeliveryDate:                       'Предпочтительные дата и время доставки',
    DeliveryTime:                       'Предпочтительное время доставки',
    fullName:                           'ФИО',
    first_name:                         'Имя',
    last_name:                          'Фамилия',
    address1:                           'Адрес',
    address2:                           'Адрес (дополнительно)',
    postal_code:                        'Почтовый индекс',
    phone:                              'Телефон',
    company:                            'Название компании',
    comments:                           'Примечание',
    recentlyViewed:                     'Недавно просмотренные',
    loading:                            'Загружается ...',
    optional:                           'необязательно',
    shippingTo:                         'Доставка',
    shippingMethods:                    'Варианты доставки',
    shippingNpOffice:                   'Отделение "Новой почты"',
    paymentMethods:                     'Варианты оплаты',
    orderSubmit:                        'Разместить заказ',
    emptyCheckout:                      'Ваша корзина пуста',
    required:                           'Заполните это поле.',
    emailInvalid:                       'Пожалуйста, укажите email правильно.',
    sameAsShipping:                     'Такой же, что и адрес доставки',
    edit:                               'Изменить',
    next:                               'Далее',
    sended:                             'Отправлено',
    send:                               'Отправить',
    login:                              'Вход',
    register:                           'Регистрация',
    login_title:                        'Вход',
    register_title:                     'Регистрация',
    login_success:                      'Вы успешно вошли в систему.',
    login_failed:                       'Неверный адрес электронной почты или пароль. Пожалуйста, попробуйте еще раз.',
    registry_success:                   'Вы успешно зарегистрировались.',
    registry_failed:                    'Указанный email адрес уже зарегистрирован. Попробуйте указать другой email.',
    registry_doi_success:               'Спасибо за регистрацию. Мы отправили письмо на Ваш email, активируйте аккуант, ссылка на активацию в отправленном письме.',
    registry_completed:                 'Вы успешно завершили регистрацию. Теперь Вы можете зайти в свой аккаунт.',
    registry_wrong_token:               'Указанный URL адрес неверный.',
    customerDetails:                    'Контактные данные',
    payment:                            'Оплата',
    welcome:                            'Добро пожаловать ',
    profile:                            'Профиль',
    orders:                             'Заказы',
    continueshopping:                   'Продолжить покупки',
    member_since:                       'Дата регистрации: ',
    account_profile_headline:           'Персональная информация',
    account_billing_headline:           'Адрес покупателя',
    empty:                              '- нет данных -',
    list_empty:                         'Нет товаров',
    logout:                             'Выйти',
    order_history:                      'История заказов',
    save:                               'Сохранить',
    password_verify_failed:             'Пароли не совпадают',
    edit_profile:                       'Редактировать персональную информацию',
    forgot_password:                    'Забыли пароль?',
    forgot_password_subtitle:           'Пожалуйста, укажите Ваш email адрес. Мы отправим Вам письмо с новым паролем.',
    forgot_password_subtitle_phone:     'Пожалуйста, укажите Ваш номер телефона. Мы отправим Вам SMS с новым паролем.',
    forgot_password_submit:             'Отправить',
    submit:                             'Отправить',
    continue_guest_headline:            'Оформить без регистрации',
    continue_guest_text:                '- Вы можете оформить заказ без регистрации.',
    forgot_password_email_sent_success: 'Спасибо. Мы отправили Вам письмо с новым паролем.',
    forgot_password_email_sent_failed:  'Указанный email адрес не зарегистрирован в нашем магазине. Укажите правильный email адрес, который был ранее зарегистрирован в нашем магазине.',
    forgot_password_phone_sent_success: 'Спасибо. Мы отправили Вам SMS с новым паролем.',
    forgot_password_phone_sent_failed:  'Указанный номер телефона не зарегистрирован в нашем магазине. Укажите правильный номер телефона, который был ранее зарегистрирован в нашем магазине.',
    reset_password:                     'Сброс пароля',
    reset_password_subtitle:            'Теперь Вы можете указать новый пароль для входа.',
    reset_password_subtitle_success:    'Ваш пароль успешно изменён.',
    back_to_login:                      'Вернуться на страницу входа',
    no_image:                           'Нет картинки',
    no_data:                            'Нет данных',
    check_delivery:                     'Проверить наличие',
    yes:                                'Да',
    no:                                 'Нет',
    all:                                'Все',
    slug:                               'Адрес страницы',
    enabled:                            'Включен',
    draft:                              'Черновик',
    description:                        'Характеристики',
    metaDescription:                    'Meta Description',
    pageTitle:                          'Заголовок страницы',
    seo:                                'Поисковая оптимизация',
    currency:                           'Валюта',
    images:                             'Изображения',
    selected:                           'выбранно',
    content:                            'Контент',
    cancel:                             'Отмена',
    add:                                'Добавить',
    actions_delete:                     'Удалить',
    actions_remove:                     'Удалить',
    actions_moveHere:                   'Переместить сюда',
    actions_moveTo:                     'Переместить в',
    actions_moveUp:                     'Поднять вверх',
    actions_moveDown:                   'Опустить вниз',
    actions_done:                       'Готово',
    actions_upload:                     'Загрузить',
    discardDraft:                       'Удалить черновик',
    actions_loadMore:                   'Показать еще',
    messages_saving:                    'Сохранение...',
    messages_saved:                     'Сохранено',
    messages_loading:                   'Загрузка...',
    messages_uploading:                 'Загрузка...',
    messages_uploadComplete:            'Загрузка завершена',
    messages_deleteConfirmation:        'Вы уверены, что хотите удалить этот элемент?',
    messages_deleteForever:             'Удалить навсегда?',
    help_dropHere:                      'Перетащите файлы сюда для загрузки',
    help_slug:                          'Адрес страницы это часть URL страницы. Обычно это строчный регистр и содержит только буквы, цифры и дефисы.',
    errors_required:                    'Это поле обязательно к заполнению.',
    errors_email:                       'Пожалуйста, введите корректный адрес электронной почты.',
    errors_url:                         'Пожалуйста, введите корректный URL.',
    errors_number:                      'Пожалуйста, введите корректное число.',
    errors_mobile:                      'Пожалуйста, введите корректный номер телефона.',
    errors_urlTaken:                    'URL занят или содержит зарезервированное слово',
    errors_toShort:                     'Слишком короткое слово',
    errors_toLong:                      'Слишком длинное слово',
    loginTitle:                         'Войти',
    loginDescription:                   'Введите свой адрес электронной почты, для отправки ссылки для входа.',
    loginButton:                        'Отправить',
    loginLinkSent:                      'На ваш адрес электронной почты была отправлена ссылка для входа',
    products_title:                     'Товары',
    products_titleEdit:                 'Редактирование товара',
    products_name:                      'Название товара',
    products_sku:                       'Артикул',
    products_stock:                     'Склад',
    products_price:                     'Цена',
    products_outOfStock:                'Нет на складе',
    products_backorder:                 'Заказ без наличия',
    products_preorder:                  'Предзаказ',
    products_inStock:                   'Есть на складе',
    products_stockStatus:               'Наличие',
    products_discontinued:              'Снят с продажи',
    products_onSale:                    'Скидка',
    products_search:                    'Поиск товаров',
    products_aboutDelete:               '{count} товары будут удалены безвозвратно. Вы не сможете отменить это действие.',
    products_regularPrice:              'Цена',
    products_salePrice:                 'Цена со скидкой',
    products_dateStockExpected:         'Ожидаемая дата',
    products_stockTracking:             'Управлять складом',
    products_stockPreorder:             'Предзаказ',
    products_stockBackorder:            'Разрешить покупку если нет в наличии',
    products_stockQuantity:             'Количество товара',
    products_weight:                    'Вес',
    products_dateSaleFrom:              'Скидка с',
    products_dateSaleTo:                'Скидка по',
    products_pricing:                   'Цены',
    products_visibility:                'Отображение',
    products_inventory:                 'Наличие',
    products_attributes:                'Свойства',
    productCategories_title:            'Категории товаров',
    productCategories_titleAdd:         'Добавить категорию',
    productCategories_titleEdit:        'Редактировать категорию',
    productCategories_titleEditMany:    'Управление категориями',
    productCategories_name:             'Название категории',
    productCategories_all:              'Все товары',
    productCategories_root:             'Корень',
    productCategories_aboutDelete:      'Категория {name} будет удалена со всеми подкатегорими.',
    settings_themeExportDesciption:     'Скачать шаблон как zip архив.',
    settings_themeInstallDesciption:    'Установить шаблон из zip архива. Может занять 2-10 мин.',
    settings_themeExport:               'Скачать',
    settings_themeInstall:              'Установить',
    settings_themeExporting:            'Экспорт...',
    settings_themeInstalling:           'Установка...',
    settings_theme:                     'Шаблон',
    settings_general:                   'Общие',
    settings_payments:                  'Оплата',
    settings_shipping:                  'Доставка',
    settings_checkout:                  'Оформление заказа',
    settings_emails:                    'Электронная почта',
    settings_taxes:                     'Налоги',
    settings_security:                  'Безопасность',
    settings_currencyFormatting:        'Формат валюты',
    settings_currencySymbol:            'Символ валюты',
    settings_thousandSeparator:         'Разделитель тысяч',
    settings_decimalSeparator:          'Разделитель десятичных',
    settings_numberOfDecimal:           'Количество десятичных',
    settings_timezone:                  'Временная зона',
    settings_dateFormat:                'Формат даты',
    settings_timeFormat:                'Формат времени',
    settings_weightUnit:                'Единицы измерения веса',
    settings_lengthUnit:                'Единицы измерения длины',
    settings_defaultProductSorting:     'Сортировака товаров по умолчанию',
    settings_sortByPriceAsc:            'Сортировать по цене (убывание)',
    settings_sortByPriceDesc:           'Сортировать по цене (возрастание)',
    settings_sortByDefault:             'По умолчанию',
    settings_enableStockManagement:     'Включить управление складом',
    settings_minimumOrderSubtotal:      'Минимальная сумма заказа',
    settings_defaultShippingCountry:    'Страна доставки по умолчанию',
    settings_defaultShippingState:      'Область/Регион доставки по умолчанию',
    settings_defaultShippingCity:       'Город доставки по умолчанию',
    settings_centimeter:                'сантиметр',
    settings_inch:                      'дюйм',
    settings_gram:                      'грамм',
    settings_kilogram:                  'килограмм',
    settings_pound:                     'фунт',
    settings_ounce:                     'унция',
    settings_smtpSettings:              'Сервер исходящей почты (SMTP)',
    settings_smtpHost:                  'SMTP сервер',
    settings_smtpPort:                  'Порт',
    settings_smtpUser:                  'Имя пользователя',
    settings_smtpPass:                  'Пароль',
    settings_emailFromName:             'Имя отправителя (отоблражается в письме)',
    settings_emailFromAddress:          'Email отправителя (От кого)',
    settings_emailSettings:             'Настройки электронной почты',
    settings_generalSettings:           'Общие настройки',
    settings_themeSettings:             'Настройки шаблона',
    settings_checkoutSettings:          'Настройки оформление заказа',
    settings_emailTemplates:            'Шаблоны писем',
    settings_orderConfirmation:         'Подтверждение заказа',
    settings_customerRegistration:      'Регистрация клиента',
    settings_customerRecovery:          'Восстановление клиента',
    settings_emailSubject:              'Тема',
    settings_emailBody:                 'Тело письма (HTML)',
    settings_shippingMethods:           'Способы доставки',
    settings_paymentsMethods:           'Способы оплаты',
    settings_editShippingMethod:        'Редактирование способа доставки',
    settings_editPaymentMethod:         'Редактирование способа оплаты',
    settings_addShippingMethod:         'Добавление способа доставки',
    settings_addPaymentMethod:          'Добавление способа оплаты',
    settings_shippingMethodName:        'Название способа доставки',
    settings_paymentMethodName:         'Название способа оплаты',
    settings_shippingRate:              'Стоимость доставки',
    settings_freeShippingRate:          'Бесплатная доставка',
    settings_conditions:                'Условия',
    settings_countries:                 'Страны',
    settings_states:                    'Области/Регионы',
    settings_cities:                    'Города',
    settings_minTotalWeight:            'Минимальный общий вес',
    settings_maxTotalWeight:            'Максимальный общий вес',
    settings_minSubtotal:               'Минимальная сумма',
    settings_maxSubtotal:               'Максимальная сумма',
    settings_onlyShippingMethods:       'Только для выбранных способов доставки',
    settings_aboutDeletePaymentMethod:  'Удалить способ оплаты {name}.',
    settings_aboutDeleteShippingMethod: 'Удалить способ доставки {name}.',
    settings_checkoutFields:            'Поля оформления заказа',
    settings_fieldStatus:               'Статус поля',
    settings_fieldRequired:             'Обязательный',
    settings_fieldOptional:             'Необязательный',
    settings_fieldHidden:               'Скрытый',
    settings_fieldLabel:                'Метка',
    settings_fieldPlaceholder:          'Заполнитель',
    settings_pages:                     'Страницы',
    settings_addPage:                   'Добавить страницу',
    settings_editPage:                  'Редактирование страницы',
    settings_aboutDeletePage:           'Удалить страницу {name}.',
    settings_tokens:                    'Маркеры доступа',
    settings_editToken:                 'Редактировать маркер доступа',
    settings_addToken:                  'Новый маркер доступа',
    settings_tokenName:                 'Название маркера',
    settings_tokenExp:                  'Время жизни маркера (час)',
    settings_selectScopes:              'Права доступа',
    settings_revokeAccess:              'Отменить доступ',
    settings_generateToken:             'Сгенерировать маркер',
    settings_tokenHelp:                 'Маркеры доступа используются для авторизации и доступа к API.',
    settings_copyYourNewToken:          'Убедитесь что вы скопировали и сохранили маркер доступа. Вы больше не сможете его увидеть!',
    settings_tokenRevokeTitle:          'Вы действительно хотите удалить этот маркер?',
    settings_tokenRevokeDescription:    'Программы и пользователи которые использовали этит маркер не смогут получить доступ к API или панели управления. Вы не сможете отменить это действие.',
    drawer_title:                       'Меню',
    drawer_home:                        'Главная',
    drawer_products:                    'Товары',
    drawer_categories:                  'Категории',
    drawer_orders:                      'Заказы',
    drawer_orderCategories:             '-',
    drawer_customers:                   'Клиенты',
    drawer_settings:                    'Настройки',
    drawer_logout:                      'Выйти',
    drawer_discounts:                   'Скидки',
    drawer_reports:                     'Отчеты',
    customers_title:                    'Клиенты',
    customer:                           'Клиент',
    customers_titleAdd:                 'Добавить нового клиента',
    customers_titleEdit:                'Редактирование клиента',
    customers_name:                     'Имя клиента',
    customers_aboutDelete:              '{count} клиенты будут удалены безвозвратно. Вы не сможете отменить это действие.',
    customers_totalSpent:               'Расход',
    customers_orders:                   'Заказы',
    customers_location:                 'Место нахождения',
    customers_search:                   'Поиск клиентов',
    customers_setGroup:                 'Изменить группу',
    customers_noGroup:                  'Нет группы',
    customerGroups_title:               'Группы клиентов',
    group:                              'Группа',
    customerGroups_titleAdd:            'Создать новую группу',
    customerGroups_titleEdit:           'Редактировать группу',
    customerGroups_titleEditMany:       'Редактировать группы',
    customerGroups_name:                'Название группы',
    customerGroups_all:                 'Все клиенты',
    customerGroups_aboutDelete:         'Удалить группу {name}.',
    orders_title:                       'Заказы',
    orders_titleAdd:                    'Создать заказ',
    orders_name:                        '-',
    orders_aboutDelete:                 '{count} заказы будут удалены безвозвратно. Вы не сможете отменить это действие.',
    orders_total:                       'Сумма',
    order:                              'Заказ',
    orders_status:                      'Статус',
    orders_date:                        'Дата',
    orders_products:                    'Товары',
    orders_client:                      'Клиент',
    orders_shippingTo:                  'Доставка',
    orders_closed:                      'Закрыт',
    orders_cancelled:                   'Отменен',
    orders_delivered:                   'Доставлен',
    orders_paid:                        'Оплачен',
    orders_hold:                        'Остановлен',
    orders_draft:                       'Черновик',
    orders_search:                      'Поиск заказов',
    pageNotFound:                       'Страница не найдена!',
    skuTaken:                           'Артикул товара должен быть уникальный',
    editProductOption:                  'Редактировать опцию',
    productVariants:                    'Варианты',
    addVariant:                         'Добавить вариант',
    addOption:                          'Добавить опцию',
    logo:                               'Логотип',
    chooseImage:                        'Выберите файлы',
    position:                           'Позиция',
    optionName:                         'Название опции',
    optionControl:                      'Компонент выбора опции',
    optionControlSelect:                'Выпадающий список',
    optionValues:                       'Значения опции',
    newOptionValue:                     'Новое значение',
    deleteProduct:                      'Удалить товар',
    domain:                             'Домен',
    manageOrderStatuses:                'Редактировать статусы',
    orderDate:                          'Дата заказа',
    orderStatus:                        'Статус заказа',
    referrer:                           'Источник',
    trackingNumber:                     'Номер отслеживания',
    shippingStatus:                     'Статус доставки',
    paymentsMethod:                     'Способ оплаты',
    customerComment:                    'Комментарии',
    orderSubtotal:                      'Сумма',
    orderShipping:                      'Доставка',
    orderTax:                           'Налог',
    orderDiscount:                      'Скидка',
    amountPaid:                         'Оплачено',
    coupon:                             'Купон',
    editOrderItem:                      'Изменить позицию заказа',
    addOrderItem:                       'Добавить товар',
    quantity:                           'Количество',
    deleteOrder:                        'Удалить заказ',
    closeOrder:                         'Закрыть заказ',
    cancelOrder:                        'Отменить заказ',
    holdOrder:                          'Остановить заказ',
    resumeOrder:                        'Возобновить заказ',
    deleteOrderConfirmation:            'Удалить заказ безвозвратно? Вы не сможете отменить это действие.',
    closeOrderConfirmation:             'Закрыть заказ? Вы не сможете отменить это действие.',
    cancelOrderConfirmation:            'Отменить заказ? Все товары вернуться на склад вашего магазина. Вы не сможете отменить это действие.',
    placeOrder:                         'Разместить заказ',
    viewOnWebsite:                      'Посмотреть на сайте',
    hideBillingAddress:                 'Не запрашивать платежный адрес при заказе',
    note:                               'Заметка',
    address:                            'Адрес',
    editAddress:                        'Изменить адрес',
    setDefaultBillingAddress:           'Установить как платежный адрес по умолчанию',
    setDefaultShippingAddress:          'Установить как адрес доставки по умолчанию',
    attributeName:                      'Название свойства',
    attributeValue:                     'Значение свойства',
    addAttribute:                       'Добавить свойство',
    newOrderReceived:                   'Поступил новый заказ',
    orderEmailCopyTo:                   'Отправить копию заказа на',
    allOrderStatuses:                   'Все статусы',
    orderStatusName:                    'Название статуса',
    orderStatusDeleteAsk:               'Удалить статус {name}.',
    orderStatuses:                      'Статусы заказа',
    editOrderStatus:                    'Редактировать статус',
    noOrderStatus:                      'Нет статуса',
    apps:                               'Приложения',
    webstoreLoginTitle:                 'Магазин приложений',
    account:                            'Профиль',
    developerProfile:                   'Профиль разработчика',
    shopUrl:                            'URL магазина',
    adminUrl:                           'URL панели',
    isDeveloper:                        'Я разработчик',
    website:                            'Веб-сайт',
    actions:                            'Действия',
    enable:                             'Включить',
    disable:                            'Выключить',
    serviceActions:                     'Действия',
    serviceLogs:                        'Журнал событий',
    paymentGateway:                     'Платежная система',
    themeSettings:                      'Настройки шаблона',
    fieldKey:                           'Идентификатор',
    additionalInfo:                     'Дополнительная информация',
    tags:                               'Теги',
    newTag:                             'Новый тег...',
    tokenExpired:                       'Маркер доступа не действителен',
    tokenInvalid:                       'Просроченный маркер доступа',
    productFields:                      'Поля товара',
    productsLimit:                      'Количество товара за один запрос',
    loadFromWebstore:                   'Чтобы загрузить приложения из WebStore, пожалуйста, войдите.',
    addProduct:                         'Добавить новый товар',
    addOrderStatus:                     'Добавить новый статус',
    dashboard:                          'Панель управления',
    files:                              'Файлы',
    fileName:                           'Название файла',
    fileModified:                       'Изменен',
    fileSize:                           'Размер',
    salesReport:                        'Продажи',
    closedAndPaidOrders:                'Закрытые и оплаченные заказы',
    newOrders:                          'Новые заказы',
    singleDeleteTitle:                  'Вы действительно хотите удалить "{name}"?',
    singleDeleteDescription:            'Этот элемент будет удален безвозвратно. Вы не сможете отменить это действие.',
    multipleDeleteTitle:                'Вы действительно хотите удалить {count} выбранных элементов?',
    multipleDeleteDescription:          '{count} элементов будут удалены безвозвратно. Вы не можете отменить это действие.',
    redirects:                          'Редиректы',
    redirectsAbout:                     'Редиректы позволяют перенести адреса страниц со старого сайта. Каждый редирект будет возвращать 301 код ответа.',
    redirectEdit:                       'Изменить редирект',
    redirectAdd:                        'Добавить редирект',
    webhooks:                           'Уведомления о событиях',
    webhooksAbout:                      'Webhook - позволяет уведомлять внешние службы о возникновении определенных событий. Когда указанные события произойдут, будет отправлен запрос POST на каждый из ваших URL-адресов.',
    webhookEdit:                        'Редактирование Webhook',
    webhookAdd:                         'Новый Webhook',
    webhookEvents:                      'События',
    webhookSecret:                      'Секретный ключ',
    themeInstalled:                     'установка завершена',
    category:                           'Категория',
    additionalCategories:               'Дополнительные категории',
    alt:                                'Атрибут alt',
    oneClickText:                       'Мгновенный заказ',
    multiCanal:                         'многоканальный',
    fullShippingMethod:         {
        'pickup.pickup': 'Самовывоз из магазина',
        'citylink.citylink': 'Доставка курьером (по Киеву)',
        'free.free': 'Доставка на склад "Новая почта"',
        'free.courier': 'Доставка курьером "Новой Почты"',
        'free.mini': 'Доставка в почтомат "Новой Почты"',
    },
    fullPaymentMethod:         {
        cod: 'Оплата при получении товара',
        cod_card: 'На карту Приватбанка',
        cheque: 'По счету фактуре',
    },
    contacts: {
        label1: 'Звоните/пишите нам:',
        label2: 'Приходите к нам:',
        label3: 'Факс',
        label4: 'E-mail',
        label5: 'Сервисный центр',
        label6: 'Наши реквизиты:',

    },
    contactsPage: 'Наши контакты',
    contactsFooter: 'Kонтакты',
    contactsSeo: 'Обратная связь',
    seoTitle: 'Интернет-магазин бытовой техники и электроники Comtrading.ua',
    seoDescription: 'Интернет-магазин Comtrading.ua ✓ Бытовая и компьютерная техника ✓ Аудио-видеоаппаратура ✓ Телефоны, смартфоны ✓Товары для спорта.',
    menu: 'Меню',
    phones_label: 'Телефоны для заказа',
    stock_status: {
        5: 'Нет в наличии',
        6: 'Под заказ (1-3 дня)',
        7: 'В наличии',
        10: 'Уточняйте',
    },
    stock_status_code: {
        5: 'out_of_stock',
        6: 'pre_order',
        7: 'available',
        10: 'precise',
    },
    searchedCategories: 'Категории товаров:',
    totalItems: 'Всего найдено ',
    totalItemsSuffix: ' товаров',
    loginText: 'В связи с обновлением магазина личный кабинет временно не доступен. Вся история заказов будет сохранена и доступна по окончанию работ. Мы искренне сожалеем о доставленных неудобствах.',
    actionTitle: 'Акция!',
    action: 'Акция',
    'model': 'Код товара (item code): ',
    'slider_title': 'Уникальные условия покупки оборудования для майнинга!',
    'slider_text': 'Уважаемые клиенты, мы понимаем, что при подборе комплектующих для построения майнинговых систем, очень важным критерием является максимальная рентабельность каждого компонента! И в то же время всегда удобнее покупать полный комплект в одном месте. Поэтому предлагаем вам возможность мотивированного, с указанием цен конкурентов, понижения цены. С полным перечнем оборудования можно ознакомится тут',
    'search_no_items': 'Ничего не найдено',
    'cartWarning': 'Внимание! В корзине произошли изменения.',
    'mustDeleteItem': 'Для продолжения удалите отсутствующие товары с корзины',
    'review': 'Отзывы',
    'review_list': 'Отзывы с площадок партнеров:',
    'review_list_empty': 'Отзывов нет',
    'rating': 'Оценка:',
    'reviewPros': 'Преимущества:',
    'reviewCons': 'Недостатки:',
    'wrong_password': 'Неправильный пароль',
    'wrong_email': 'Неправильный email',
    'wrong_mobile': 'Неправильный номер телефона',
    'wrong_edit': 'Ошибка редактирования данных',
    'my_account': 'Моя учетная запись',
    'change_account': 'Изменить контактную информацию',
    'change_password': 'Изменить свой пароль',
    'change_address': 'Изменить мой адрес',
    'my_orders': 'Мои заказы',
    'newsletter': 'Подписка',
    'my_newsletter': 'Подписаться или отказаться от рассылки новостей',
    'AccountEdit': 'Учетная запись',
    'edit_success': 'Данные успешно обновлены',
    'AccountPassword': 'Изменить пароль',
    'newPassword': 'Новый пароль',
    'newPasswordConfirm': 'Подтвердите пароль',
    'errors_password_confirm': 'Пароли не совпадают',
    'order_details': 'Детали заказа',
    'order_id': '№ Заказа:',
    'order_date': 'Добавлено:',
    'order_payment': 'Способ оплаты:',
    'order_shipping': 'Способ доставки:',
    'order_payment_address': 'Платёжный адрес',
    'order_shipping_address': 'Адрес доставки',
    'order_product_name': 'Название товара',
    'order_product_model': 'Модель',
    'order_product_quantity': 'Количество',
    'order_product_price': 'Цена',
    'order_product_total': 'Всего',
    'showSuppliers': 'Показать поставщиков',
    'suppliers': 'Поставщики:',
    'rrc_price': 'Цена с выкл. РРЦ: ',
    'rrc_price_in': 'Цена с РРЦ: ',
    'sale_title':  'Гарантия лучшей цены',
    'sale_description': 'Интернет-магазин Comtrading.ua заказать товары с гарантией лучшей цены.',
    'sale_slogan': 'Мы гарантируем максимально низкую цену на товары в данной категории. Найдите в интернете цену ниже и мы ее повторим!',
    'best_price': 'Лучшая цена',
    'fixed_text': 'Стоимость',
    'fixed_price': 'зафиксирована',
    'fixed_available_text': 'Наличие зафиксировано до',
    'compare': 'Сравнение',
    'compareEmpty': 'Нет товаров для сравнения',
    comparison: 'Сравниваем ',
    pn: 'PN: ',
    product_model: 'Код производителя: ',
    clearFilters: 'Очистить',
    onlyId: 'Только ID',
    creditText: 'Купить в рассрочку',
    stockBtn: 'Сообщить о наличии',
    serviceBtn: 'Сообщить о проблеме',
    serviceFormTitle: 'Сообщить о проблеме',
    orderId: '№ заказа',
    request: 'Ваш запрос',
    serviceSuccessTitle: 'Спасибо за ваше обращение!',
    serviceSuccessText: 'Ваша заявка получена и поступит в обработку в ближайшее время.',
    agreement_text: 'Я принимаю условия пользовательского ',
    agreement: 'соглашения',
    cashless: 'Безналичный',
    cash: 'Наличный',
    showOptPrices: 'Показать цены',
    cashless_price: 'Цена безнал: ',
    cartWarningCheque: 'Внимание цены в корзине изменены в соответствии с выбранным способом оплаты',
    cashlessWarning: 'Данный товар не доступен с выбранной формой оплаты',
    cashlessCheckbox: 'Только б/н цены',
    prices: 'Скачать прайс',
    filter_cancel: 'Сбросить',
    filter_accept: 'Применить',
    for_mining: ' Для майнинга',
    mining: 'Комплектующие для майнинга',
    fixed_rrc_date: 'РРЦ зафиксирован до ',
    analyse: 'Анализ цен',
    search_name: 'Имя, Фамилия',
    usersNotFound: 'Пользователь не найден.',
    showHistory: 'Просмотреть историю',
    userOrdersNotFound: 'Заказы пользователя не найдены.',
    login_by_phone: 'Войти по номеру телефона',
    login_by_email: 'Войти по email',
    forgot_by_phone: 'Ввести номер телефона',
    forgot_by_email: 'Ввести email'
};

export const themeSettings = {
    checkoutInputClass:      'checkout-field',
    checkoutButtonClass:     'checkout-button button is-primary',
    checkoutEditButtonClass: 'checkout-button button',
    cartThumbnailWidth:      '212x160',
    footer_contacts:         [
        {text: '104 N Stagecoach Rd'},
        {text: 'Dover Foxcroft, ME, 04426'},
        {text: '(207) 564-8482'},
        {text: 'sales@shop.com'},
    ],
    footer_about:        'Store - just to show you what it can. Some text go here. Some text go here. Some text go here. Some text go here. Some text go here. Some text go here. Some text go here.',
    footer_menu_2_title: 'Customer service',
    footer_menu_1_title: 'Company',
    footer_social:       [
        {type: 'facebook',
            url:  'https://www.facebook.com/'},
        {type: 'twitter',
            url:  'https://twitter.com/'},
    ], footer_menu_1_items: [
        {text: 'About',
            url:  '/about'},
        {text: 'Blog',
            url:  '/blog'},
        {text: 'Terms of Service', url: '/tos'},
        {text: 'Privacy Policy', url: '/privacy-policy'},
    ], footer_menu_2_items: [
        {text: 'Shipping & returns', url: '/'},
        {text: 'Conditions of Use',
            url:  '/'},
        {text: 'Sitemap', url: '/'},
    ], search_placeholder:  '',
    home_products_limit: 8,
    home_products_title: 'Новинки',
    home_products_sale: 'Распродажа',
    popular_products_title: 'Популярные товары',
    home_products_sort:  '-date_updated',
    home_slider:         [
        {
            image: '/assets/images/banners/01.jpg',
            path:  '/prod-noutbuk-dell-g3-3579-g35781s1ndl-60b-black-170524/'
        },
        {
            image: '/assets/images/banners/03.png',
            path:  '/prod-kuler-dlya-protsessora-deepcool-gammaxx-300-16739/'
        },
        {
            image: '/assets/images/banners/06.jpg',
            path:  '/search/?s=GAZER F7'
        },
        {
            image: '/assets/images/banners/07.jpg',
        },
        {
            image: '/assets/images/banners/08.jpg',
        },
        {
            image: '/assets/images/banners/09.jpg',
            path:  '/bytovaya-tekhnika-2/klimaticheskaya-tekhnika-59/konditsionery-68/'
        },
        {
            image: '/assets/images/banners/10.jpg',
            path:  '/gadzhety-i-aksessuary-1338/optika-1143/solntsezaschitnye-ochki-1367/'
        },
    ], home_slider_color:          '#ffffff',
    button_addtocart_text:      '',
    disqus_shortname:           'cezerin',
    maxCartItemQty:             100,
    product_thumbnail_position: 'left',
    bigThumbnailWidth:          '500x500',
    previewThumbnailWidth:      '212x160',
    list_image_max_height:      280,
    listThumbnailWidth:         '212x160',
    categoryThumbnailWidth:     '200x200',
    show_product_filter:        true,
    show_category_breadcrumbs:  true,
    show_discount_countdown:    true,
    show_product_breadcrumbs:   true,
    sortNewest:                 'date_created|-1',
    sortPriceLow:               'price|1',
    sortPriceHigh:              'price|-1',
    footer_logo_url:            '/assets/images/logo.png',
    limit_viewed_products:      4,
    show_viewed_products:       true,
    product_gallery_shownav:    true,
    page_list_tag:              'blog',
};

export const settings = {
    logo: '/assets/images/logo.png',
    logo_ktk: '/assets/images/logo_ktk.png',
    store_name: 'Comtrading',
    domain: '',
    logo_file: '/assets/images/logo.png',
    language: 'ru',
    currency_code: 'UAH',
    currency_symbol: '₴',
    currency_format: '{amount}₴',
    currency_format_usd: `\${amount}`,
    thousand_separator: ' ',
    decimal_separator: '.',
    decimal_number: 0,
    tax_rate: 0,
    tax_included: true,
    timezone: 'Europe/Kiev',
    date_format: 'MMMM D, YYYY',
    time_format: 'h:mm a',
    default_shipping_country: '',
    default_shipping_state: '',
    default_shipping_city: '',
    default_product_sorting: 'price',
    default_search_sorting: '_scores',
    default_product_order: 1,
    product_fields:
        'path,id,name,category_id,category_name,sku,image,images,enabled,discontinued,stock_status,stock_quantity,price,on_sale,regular_price,attributes,tags,position',
    products_limit: 24,
    weight_unit: 'kg',
    length_unit: 'cm',
    hide_billing_address: false,
    order_confirmation_copy_to: '',
    shippingMethodPrice:         {
        'pickup.pickup': 0,
        'citylink.citylink': 100,
        'free.free': 0,
        'free.courier': 0,
        'free.mini': 0,
    },
};